run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/crossplane-contrib/provider-discord
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/crossplane/crossplane-runtime/pkg/logging.Logger).Debug
          - (github.com/crossplane/crossplane-runtime/pkg/logging.Logger).Info
          - (github.com/crossplane/crossplane-runtime/pkg/logging.Logger).WithValues
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  exclude-rules:
    - path: zz_generated\.deepcopy\.go
      linters:
        - lll
    - path: zz_generated\.managed\.go
      linters:
        - lll
    - path: zz_generated\.managedlist\.go
      linters:
        - lll
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - lll

  exclude:
    # Crossplane runtime uses a lot of reflection which golangci-lint
    # doesn't understand
    - "reflect.*never returns"