//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Invite) DeepCopyInto(out *Invite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Invite.
func (in *Invite) DeepCopy() *Invite {
	if in == nil {
		return nil
	}
	out := new(Invite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Invite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteList) DeepCopyInto(out *InviteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Invite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteList.
func (in *InviteList) DeepCopy() *InviteList {
	if in == nil {
		return nil
	}
	out := new(InviteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InviteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteObservation) DeepCopyInto(out *InviteObservation) {
	*out = *in
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(int)
		**out = **in
	}
	if in.TargetUserID != nil {
		in, out := &in.TargetUserID, &out.TargetUserID
		*out = new(string)
		**out = **in
	}
	if in.TargetApplicationID != nil {
		in, out := &in.TargetApplicationID, &out.TargetApplicationID
		*out = new(string)
		**out = **in
	}
	if in.ApproximatePresenceCount != nil {
		in, out := &in.ApproximatePresenceCount, &out.ApproximatePresenceCount
		*out = new(int)
		**out = **in
	}
	if in.ApproximateMemberCount != nil {
		in, out := &in.ApproximateMemberCount, &out.ApproximateMemberCount
		*out = new(int)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteObservation.
func (in *InviteObservation) DeepCopy() *InviteObservation {
	if in == nil {
		return nil
	}
	out := new(InviteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteParameters) DeepCopyInto(out *InviteParameters) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(int)
		**out = **in
	}
	if in.MaxUses != nil {
		in, out := &in.MaxUses, &out.MaxUses
		*out = new(int)
		**out = **in
	}
	if in.Temporary != nil {
		in, out := &in.Temporary, &out.Temporary
		*out = new(bool)
		**out = **in
	}
	if in.Unique != nil {
		in, out := &in.Unique, &out.Unique
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteParameters.
func (in *InviteParameters) DeepCopy() *InviteParameters {
	if in == nil {
		return nil
	}
	out := new(InviteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteSpec) DeepCopyInto(out *InviteSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteSpec.
func (in *InviteSpec) DeepCopy() *InviteSpec {
	if in == nil {
		return nil
	}
	out := new(InviteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InviteStatus) DeepCopyInto(out *InviteStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InviteStatus.
func (in *InviteStatus) DeepCopy() *InviteStatus {
	if in == nil {
		return nil
	}
	out := new(InviteStatus)
	in.DeepCopyInto(out)
	return out
}
