apiVersion: discord.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: discord-creds
      key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: discord-creds
  namespace: crossplane-system
type: Opaque
data:
  # Base64 encoded Discord bot token
  # kubectl create secret generic discord-creds -n crossplane-system --from-literal=token=YOUR_BOT_TOKEN
  token: ""
