//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Guild) DeepCopyInto(out *Guild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Guild.
func (in *Guild) DeepCopy() *Guild {
	if in == nil {
		return nil
	}
	out := new(Guild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Guild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuildList) DeepCopyInto(out *GuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Guild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuildList.
func (in *GuildList) DeepCopy() *GuildList {
	if in == nil {
		return nil
	}
	out := new(GuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuildObservation) DeepCopyInto(out *GuildObservation) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuildObservation.
func (in *GuildObservation) DeepCopy() *GuildObservation {
	if in == nil {
		return nil
	}
	out := new(GuildObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuildParameters) DeepCopyInto(out *GuildParameters) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.VerificationLevel != nil {
		in, out := &in.VerificationLevel, &out.VerificationLevel
		*out = new(int)
		**out = **in
	}
	if in.DefaultMessageNotifications != nil {
		in, out := &in.DefaultMessageNotifications, &out.DefaultMessageNotifications
		*out = new(int)
		**out = **in
	}
	if in.ExplicitContentFilter != nil {
		in, out := &in.ExplicitContentFilter, &out.ExplicitContentFilter
		*out = new(int)
		**out = **in
	}
	if in.AFKChannelID != nil {
		in, out := &in.AFKChannelID, &out.AFKChannelID
		*out = new(string)
		**out = **in
	}
	if in.AFKTimeout != nil {
		in, out := &in.AFKTimeout, &out.AFKTimeout
		*out = new(int)
		**out = **in
	}
	if in.SystemChannelID != nil {
		in, out := &in.SystemChannelID, &out.SystemChannelID
		*out = new(string)
		**out = **in
	}
	if in.SystemChannelFlags != nil {
		in, out := &in.SystemChannelFlags, &out.SystemChannelFlags
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuildParameters.
func (in *GuildParameters) DeepCopy() *GuildParameters {
	if in == nil {
		return nil
	}
	out := new(GuildParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuildSpec) DeepCopyInto(out *GuildSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuildSpec.
func (in *GuildSpec) DeepCopy() *GuildSpec {
	if in == nil {
		return nil
	}
	out := new(GuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuildStatus) DeepCopyInto(out *GuildStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuildStatus.
func (in *GuildStatus) DeepCopy() *GuildStatus {
	if in == nil {
		return nil
	}
	out := new(GuildStatus)
	in.DeepCopyInto(out)
	return out
}
