apiVersion: channel.discord.golder.tech/v1alpha1
kind: Channel
metadata:
  name: golder-chat-websites
  annotations:
    discord.golder.tech/id: "1218720029244264601"
spec:
  forProvider:
    name: "websites"
    type: 0
    guildId: "596248212994654225"
    position: 23
  providerConfigRef:
    name: discord-provider-config
