apiVersion: channel.discord.crossplane.io/v1alpha1
kind: Channel
metadata:
  name: golder-chat-unnamed
  annotations:
    discord.crossplane.io/id: "1044437380863639703"
spec:
  forProvider:
    name: "การแปลงสัญชาติ"
    type: 0
    guildId: "596248212994654225"
    position: 5
  providerConfigRef:
    name: discord-provider-config
