apiVersion: role.discord.m.crossplane.io/v1beta1
kind: Role
metadata:
  name: example-role-v2
  namespace: discord-resources
  annotations:
    crossplane.io/external-name: ""  # Will be set to Discord role ID after creation
spec:
  forProvider:
    name: "Crossplane Managed"
    guildId: "123456789012345678"  # Replace with actual guild ID
    color: 5814783  # Blue color (hex: #58a7ff)
    hoist: true  # Display separately from online members
    mentionable: true  # Allow role to be mentioned
    permissions: "104324161"  # Basic permissions (view channels, send messages, etc.)
    position: 1  # Position in role hierarchy
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  writeConnectionSecretsToRef:
    name: role-connection-details
    namespace: discord-resources
